# TravisCI configuration file
language: python
python:
- '3.3'
- '2.7'
install:
- pip install --upgrade -r requirements.txt
test:
- python chef-tag-api.py& 
- restafari -s localhost -P 9999 api_test/*
